#include "ft_printf.h"
#include <stdio.h>
#include <limits.h>

void	test_c(void);
void	test_s(void);
void	test_p(void);
void	test_d(void);
void	test_i(void);
void	test_u(void);
void	test_x(void);
void	test_X(void);
void	test_per(void);

int main()
{
	// test_c();
	// test_s();
	// test_p();
	// test_d();
	test_x();
}

void	test_c(void)
{
	char A = 'A';
	printf("\n========C=========\n");
	printf("%%c 0\n");
	printf("printf---->|");
	printf("%c||\n",0);
	//printf("ft_printf->|");
	//ft_printf("%c||\n",0);
	printf("===================\n");
	printf("%%-c 0\n");
	printf("printf---->|");
	printf("%-c||\n", 0);
	//printf("ft_printf->|");
	//ft_printf("-0c||\n", 0);
	printf("===================\n");
	printf("%%10c 0\n");
	printf("printf---->|");
	printf("%10c||\n",0);
	//printf("ft_printf->|");
	//ft_printf("%10c||\n",0);
	printf("===================\n");
	printf("%%-10c 0\n");
	printf("printf---->|");
	printf("%-10c||\n",0);
	//printf("ft_printf->|");
	//ft_printf("%-10c||\n",0);
	printf("===================\n");
	printf("%%c A\n");
	printf("printf---->|");
	printf("%c||\n",A);
	//printf("ft_printf->|");
	//ft_printf("%c||\n",A);
	printf("===================\n");
	printf("%%-c A\n");
	printf("printf---->|");
	printf("%-c||\n", A);
	//printf("ft_printf->|");
	//ft_printf("%-c||\n", A);
	printf("===================\n");
	printf("%%10c A\n");
	printf("printf---->|");
	printf("%10c||\n",A);
	//printf("ft_printf->|");
	//ft_printf("%10c||\n",A);
	printf("===================\n");
	printf("%%-10c A\n");
	printf("printf---->|");
	printf("%-10c||\n",A);
	//printf("ft_printf->|");
	//ft_printf("%-10c||\n",A);
	printf("===================\n");
}

void	test_s(void)
{
	printf("\n=========S=========\n");
	printf("%%s STRING\n");
	printf("printf---->|");
	printf("%s||\n", "STRING");
	//printf("ft_printf->|");
	//ft_printf("%s||\n", "STRING");
	printf("===================\n");
	printf("%%-s STRING\n");
	printf("printf---->|");
	printf("%-s||\n","STRING");
	//printf("ft_printf->|");
	//ft_printf("||\n","STRING");
	printf("===================\n");
	printf("%%10s STRING\n");
	printf("printf---->|");
	printf("%10s||\n","STRING");
	//printf("ft_printf->|");
	//ft_printf("%10s||\n", "STRING");
	printf("===================\n");
	printf("%%.5s STRING\n");
	printf("printf---->|");
	printf("%.5s||\n", "STRING");
	//printf("ft_printf->|");
	//ft_printf("%.5s||\n", "STRING");
	printf("===================\n");
	printf("%%-10s STRING\n");
	printf("printf---->|");
	printf("%-10s||\n","STRING");
	//printf("ft_printf->|");
	//ft_printf("%-10s||\n", "STRING");
	printf("===================\n");
	printf("%%10.5s STRING\n");
	printf("printf---->|");
	printf("%10.5s||\n", "STRING");
	//printf("ft_printf->|");
	//ft_printf("%10.5s||\n", "STRING");
	printf("===================\n");
	printf("%%-10.5s STRING\n");
	printf("printf---->|");
	printf("%-10.5s||\n", "STRING");
	//printf("ft_printf->|");
	//ft_printf("%-10.5s||\n", "STRING");
	printf("===================\n");	
}

void	test_p(void)
{
	int a = 0;
	printf("\n=========P=========\n");
	printf("%%p(void *)0\n");
	printf("printf---->|");
	printf("%p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%p||", (void *)0);
	printf("===================\n");
	printf("%%-p(void *)0\n");
	printf("printf---->|");
	printf("%-p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%-p||", (void *)0);
	printf("===================\n");
	printf("%%5p(void *)0\n");
	printf("printf---->|");
	printf("%5p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%5p||", (void *)0);
	printf("===================\n");
	printf("%%10p(void *)0\n");
	printf("printf---->|");
	printf("%10p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%10p||", (void *)0);
	printf("===================\n");
	printf("%%15p(void *)0\n");
	printf("printf---->|");
	printf("%15p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%15p||", (void *)0);
	printf("===================\n");
	printf("%%-10p(void *)0\n");
	printf("printf---->|");
	printf("%-10p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%-10p||", (void *)0);
	printf("===================\n");
	printf("%%-15p(void *)0\n");
	printf("printf---->|");
	printf("%-15p||\n", (void *)0);
	//printf("ft_printf->|");
	//ft_printf("%-15p||", (void *)0);
	printf("===================\n");
	printf("%%15p&a\n");
	printf("printf---->|");
	printf("%15p||\n", &a);
	//printf("ft_printf->|");
	//ft_printf("%15p||", &a);
	printf("===================\n");
	printf("%%-15p(void *)0\n");
	printf("printf---->|");
	printf("%-15p||\n", &a);
	//printf("ft_printf->|");
	//ft_printf("%-15p||", &a);
	printf("===================\n");
	printf("%%p(void *)-1\n");
	printf("printf---->|");
	printf("%p||\n", (void *)-1);
	//printf("ft_printf->|");
	//ft_printf("%p||", (void *)-1);
	printf("===================\n");
	printf("%%20p(void *)-1\n");
	printf("printf---->|");
	printf("%20p||\n", (void *)-1);
	//printf("ft_printf->|");
	//ft_printf("%20p||", (void *)-1);
	printf("===================\n");
	printf("%%p(void *)LONG_MAX\n");
	printf("printf---->|");
	printf("%p||\n", (void *)LONG_MAX);
	//printf("ft_printf->|");
	//ft_printf("%p||", (void *)LONG_MAX);
	printf("===================\n");
	printf("%%p(void *)LONG_MIN\n");
	printf("printf---->|");
	printf("%p||\n", (void *)LONG_MIN);
	//printf("ft_printf->|");
	//ft_printf("%p||", (void *)LONG_MIN);
	printf("===================\n");
}

void	test_d(void)
{
	int a = -123;
	printf("\n=========d=========\n");
	printf("%%d a \n");
	printf("printf---->|");
	printf("%d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%d||",a);
	printf("===================\n");
	printf("%%0d a \n");
	printf("printf---->|");
	printf("%0d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0d||",a);
	printf("===================\n");
	printf("%%-d a \n");
	printf("printf---->|");
	printf("%-d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%-d||",a);
	printf("===================\n");
	printf("%% d a \n");
	printf("printf---->|");
	printf("% d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("% d||",a);
	printf("===================\n");
	printf("%%+d a \n");
	printf("printf---->|");
	printf("%+d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%d||",a);
	printf("===================\n");
	printf("%%6d a \n");
	printf("printf---->|");
	printf("%6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%6d||",a);
	printf("===================\n");
	printf("%%.6d a \n");
	printf("printf---->|");
	printf("%.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%.6d||",a);
	printf("===================\n");
	printf("%%.2d a \n");
	printf("printf---->|");
	printf("%.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%.2d||",a);
	printf("===================\n");
	printf("%%0-d a \n");
	printf("printf---->|");
	printf("%0-d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-d||",a);
	printf("===================\n");
	printf("%%0 d a \n");
	printf("printf---->|");
	printf("%0 d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0 d||",a);
	printf("===================\n");
	printf("%%0+d a \n");
	printf("printf---->|");
	printf("%0+d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0+d||",a);
	printf("===================\n");
	printf("%%06d a \n");
	printf("printf---->|");
	printf("%06d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%06d||",a);
	printf("===================\n");
	printf("%%0.6d a \n");
	printf("printf---->|");
	printf("%0.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%006d||",a);
	printf("===================\n");
	printf("%%0.2d a \n");
	printf("printf---->|");
	printf("%0.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0.2d||",a);
	printf("===================\n");
	printf("%%- d a \n");
	printf("printf---->|");
	printf("%- d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%- d||",a);
	printf("===================\n");
	printf("%%-+d a \n");
	printf("printf---->|");
	printf("%-+d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%-+d||",a);
	printf("===================\n");
	printf("%%-6d a \n");
	printf("printf---->|");
	printf("%-6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%-6d||",a);
	printf("===================\n");
	printf("%%-.6d a \n");
	printf("printf---->|");
	printf("%-.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%-.6d||",a);
	printf("===================\n");
	printf("%%-.2d a \n");
	printf("printf---->|");
	printf("%-.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%-.2d||",a);
	printf("===================\n");
	printf("%% +d a \n");
	printf("printf---->|");
	printf("% +d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("% +d||",a);
	printf("===================\n");
	printf("%% 6d a \n");
	printf("printf---->|");
	printf("% 6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("% 6d||",a);
	printf("===================\n");
	printf("%% .2d a \n");
	printf("printf---->|");
	printf("% .2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("% .62||",a);
	printf("===================\n");
	printf("%% .6d a \n");
	printf("printf---->|");
	printf("% .6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("% .6d||",a);
	printf("===================\n");
	printf("%%+6d a \n");
	printf("printf---->|");
	printf("%+6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%6d||",a);
	printf("===================\n");
	printf("%%+.6d a \n");
	printf("printf---->|");
	printf("%+.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%.6d||",a);
	printf("===================\n");
	printf("%%+.2d a \n");
	printf("printf---->|");
	printf("%+.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%+.2d||",a);
	printf("===================\n");
	printf("%%6.6d a \n");
	printf("printf---->|");
	printf("%6.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%6.6d||",a);
	printf("===================\n");
	printf("%%6.2d a \n");
	printf("printf---->|");
	printf("%6.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%6.2d||",a);
	printf("===================\n");
	printf("%%0- d a \n");
	printf("printf---->|");
	printf("%0- d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- d||",a);
	printf("===================\n");
	printf("%%0-+d a \n");
	printf("printf---->|");
	printf("%0-+d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-+d||",a);
	printf("===================\n");
	printf("%%0-6d a \n");
	printf("printf---->|");
	printf("%0-6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-6d||",a);
	printf("===================\n");
	printf("%%0-.6d a \n");
	printf("printf---->|");
	printf("%0-.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-.6d||",a);
	printf("===================\n");
	printf("%%0-.2d a \n");
	printf("printf---->|");
	printf("%0-.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-.2d||",a);
	printf("===================\n");
	printf("%%0 +d a \n");
	printf("printf---->|");
	printf("%0 +d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0 +d||",a);
	printf("===================\n");
	printf("%%0 6d a \n");
	printf("printf---->|");
	printf("%0 6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0 6d||",a);
	printf("===================\n");
	printf("%%0 .6d a \n");
	printf("printf---->|");
	printf("%0 .6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0 .6d||",a);
	printf("===================\n");
	printf("%%0 .2d a \n");
	printf("printf---->|");
	printf("%0 .2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0 .2d||",a);
	printf("===================\n");
	printf("%%0+6d a \n");
	printf("printf---->|");
	printf("%0+6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0+6d||",a);
	printf("===================\n");
	printf("%%0+.6d a \n");
	printf("printf---->|");
	printf("%0+.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0+.6d||",a);
	printf("===================\n");
	printf("%%0+.2d a \n");
	printf("printf---->|");
	printf("%0+.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0+.2d||",a);
	printf("===================\n");
	printf("%%06.6d a \n");
	printf("printf---->|");
	printf("%06.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%06.6d||",a);
	printf("===================\n");
	printf("%%06.2d a \n");
	printf("printf---->|");
	printf("%06.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%06.2d||",a);
	printf("===================\n");
	printf("%%0- +d a \n");
	printf("printf---->|");
	printf("%0- +d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- +d||",a);
	printf("===================\n");
	printf("%%0- 6d a \n");
	printf("printf---->|");
	printf("%0- 6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- 6d||",a);
	printf("===================\n");
	printf("%%0- .6d a \n");
	printf("printf---->|");
	printf("%0- .6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- .6d||",a);
	printf("===================\n");
	printf("%%0- .2d a \n");
	printf("printf---->|");
	printf("%0- .2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- .2d||",a);
	printf("===================\n");
	printf("%%0-+6d a \n");
	printf("printf---->|");
	printf("%0-+6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-+6d||",a);
	printf("===================\n");
	printf("%%0-+.6d a \n");
	printf("printf---->|");
	printf("%0-+.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-+.6d||",a);
	printf("===================\n");
	printf("%%0-+.2d a \n");
	printf("printf---->|");
	printf("%0-+.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-+.2d||",a);
	printf("===================\n");
	printf("%%0-+6.6d a \n");
	printf("printf---->|");
	printf("%0-+6.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-+6.6d||",a);
	printf("===================\n");
	printf("%%0-+6.2d a \n");
	printf("printf---->|");
	printf("%0-+6.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0-+6.2d||",a);
	printf("===================\n");
	printf("%%0- +6d a \n");
	printf("printf---->|");
	printf("%0- +6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- +6d||",a);
	printf("===================\n");
	printf("%%0- +.6d a \n");
	printf("printf---->|");
	printf("%0- +.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- +.6d||",a);
	printf("===================\n");
	printf("%%0- +.2d a \n");
	printf("printf---->|");
	printf("%0- +.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- +.2d||",a);
	printf("===================\n");
	printf("%%0- +6.6d a \n");
	printf("printf---->|");
	printf("%0- +6.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- +6.6d||",a);
	printf("===================\n");
	printf("%%0- +6.2d a \n");
	printf("printf---->|");
	printf("%0- +6.2d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%0- +6.2d||",a);
	printf("===================\n");
	printf("%%8.6d a \n");
	printf("printf---->|");
	printf("%8.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%8.6d||",a);
	printf("===================\n");
	printf("%%-8.6d a \n");
	printf("printf---->|");
	printf("%-8.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%-8.6d||",a);
	printf("===================\n");
	printf("%%+8.6d a \n");
	printf("printf---->|");
	printf("%+8.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("%+8.6d||",a);
	printf("===================\n");
	printf("%% 8.6d a \n");
	printf("printf---->|");
	printf("% 8.6d||\n",a);
	//printf("ft_printf->|");
	//ft_printf("% 8.6d||",a);
	printf("===================\n");
}

void	test_i(void)
{

}

void	test_u(void)
{

}

void	test_x(void)
{
	unsigned int a = 1234;
	printf("\n=========x=========\n");
	printf("%%#x \n");
	printf("printf---->|");
	printf("%#x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#x||", a);
	printf("===================\n");
	printf("%%0x \n");
	printf("printf---->|");
	printf("%0x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%0x||", a);
	printf("===================\n");
	printf("%%-x \n");
	printf("printf---->|");
	printf("%-x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%-x||", a);
	printf("===================\n");
	printf("%%6x \n");
	printf("printf---->|");
	printf("%6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%6x||", a);
	printf("===================\n");
	printf("%%.6x \n");
	printf("printf---->|");
	printf("%.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%.6x||", a);
	printf("===================\n");
	printf("%%#0x \n");
	printf("printf---->|");
	printf("%#0x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#0x||", a);
	printf("===================\n");
	printf("%%#-x \n");
	printf("printf---->|");
	printf("%#-x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#-x||", a);
	printf("===================\n");
	printf("%%#6x \n");
	printf("printf---->|");
	printf("%#6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#6x||", a);
	printf("===================\n");
	printf("%%#.6x \n");
	printf("printf---->|");
	printf("%#.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#.6x||", a);
	printf("===================\n");
	printf("%%0-x \n");
	printf("printf---->|");
	printf("%0-x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%0-x||", a);
	printf("===================\n");
	printf("%%06x \n");
	printf("printf---->|");
	printf("%06x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%06x||", a);
	printf("===================\n");
	printf("%%0.6x \n");
	printf("printf---->|");
	printf("%0.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%0.6x||", a);
	printf("===================\n");
	printf("%%-6x \n");
	printf("printf---->|");
	printf("%-6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%-6x||", a);
	printf("===================\n");
	printf("%%-.6x \n");
	printf("printf---->|");
	printf("%-.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%-.6x||", a);
	printf("===================\n");
	printf("%%6.6x \n");
	printf("printf---->|");
	printf("%6.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%6.6x||", a);
	printf("===================\n");
	printf("%%#0-x \n");
	printf("printf---->|");
	printf("%#0-x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#0-x||", a);
	printf("===================\n");
	printf("%%#06x \n");
	printf("printf---->|");
	printf("%#06x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#06x||", a);
	printf("===================\n");
	printf("%%#0.6x \n");
	printf("printf---->|");
	printf("%#0.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#0.6x||", a);
	printf("===================\n");
	printf("%%#-6x \n");
	printf("printf---->|");
	printf("%#-6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#-6x||", a);
	printf("===================\n");
	printf("%%#-.6x \n");
	printf("printf---->|");
	printf("%#-.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#-.6x||", a);
	printf("===================\n");
	printf("%%#6.6x \n");
	printf("printf---->|");
	printf("%#6.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#6.6x||", a);
	printf("===================\n");
	printf("%%#0-6x \n");
	printf("printf---->|");
	printf("%#0-6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#0-6x||", a);
	printf("===================\n");
	printf("%%#0-.6x \n");
	printf("printf---->|");
	printf("%#0-.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#0-.6x||", a);
	printf("===================\n");
	printf("%%#0-6.6x \n");
	printf("printf---->|");
	printf("%#0-6.6x||\n", a);
	//printf("ft_printf->|");
	//ft_printf("%#0-6.6x||", a);
	printf("===================\n");
}

void	test_X(void)
{

}

void	test_per(void)
{

}